services:
  wordpress:
    image: wordpress:php8.1-fpm-alpine
    mem_limit: 256m
    container_name: salla-wordpress
    restart: always
    depends_on:
      - db
    links:
      - db
      - redis
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_REDIS_HOST', 'redis' );
    volumes:
      - wordpress:/var/www/html
      - ./config/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      - ./config/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini:ro

  db:
    image: mysql:8.0
    mem_limit: 256m
    container_name: salla-wordpress-db
    restart: always
    environment:
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - wordpress-db:/var/lib/mysql
      - ./config/custom.cnf:/etc/mysql/conf.d/custom.cnf:ro

  redis:
    image: redis:7.2-alpine
    container_name: salla-wordpress-redis
    restart: always

  nginx:
    image: nginx:1.25
    container_name: salla-wordpress-nginx
    restart: always
    environment:
      VIRTUAL_HOST: ${DOMAIN}
      LETSENCRYPT_HOST: ${DOMAIN}
    links:
      - wordpress
    volumes:
      - wordpress:/var/www/html
      - ./config/vhost.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  wordpress:
  wordpress-db:

networks:
  default:
    external: true
    name: polarix